### ISSUE TITLE
Consider define the default repository URL if not provided

### ISSUE THREAD

**Issue by bkmeneguello** [flaper87/pyhelm#20]
If no `source` is provided this module should behave just like `helm` executable and use by default
```yaml
source:
  type: repo
  location: https://kubernetes-charts.storage.googleapis.com
```
This would be simpler and more intuitive.
